{% set name = "pyppmd" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1a812f1e7628f4c26d05de340b91b72165d7b62778c27d322b82ce2e8ff00cb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy' and ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools >=45.0
    - setuptools-scm >=6.0.1
  run:
    - python
    - importlib_metadata

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pyppmd
  summary: PPMd compression/decompression library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
