{% set name = "pyppmd" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1a812f1e7628f4c26d05de340b91b72165d7b62778c27d322b82ce2e8ff00cb

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.9
    - setuptools >=59
    - setuptools-scm >=6.4.2
    - pip
  run:
    - python >=3.9

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - python >=3.9
    - pip


about:
  home: https://codeberg.org/miurahr/pyppmd
  summary: PPMd compression/decompression library
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
