{% set name = "pyppmd" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 075c9bd297e3b0a87dd7aeabca7fee668218acbe69ecc1c6511064558de8840f

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy' and ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools >=45.0
    - setuptools-scm >=6.0.1
  run:
    - python
    - importlib_metadata

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pyppmd
  summary: PPMd compression/decompression library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
